<?php

/*
 * This file is part of the puli/url-generator package.
 *
 * (c) Bernhard Schussek <bschussek@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Puli\UrlGenerator;

use InvalidArgumentException;
use Puli\Discovery\Api\Discovery;
use Puli\Repository\Discovery\ResourceBinding;
use Puli\UrlGenerator\Api\CannotGenerateUrlException;
use Puli\UrlGenerator\Api\UrlGenerator;
use Webmozart\Glob\Glob;
use Webmozart\PathUtil\Url;

/**
 * A resource URL generator that uses a {@link ResourceDiscovery} as backend.
 *
 * @since  1.0
 *
 * @author Bernhard Schussek <bschussek@gmail.com>
 */
class DiscoveryUrlGenerator implements UrlGenerator
{
    /**
     * The binding type of public resources.
     */
    const BINDING_TYPE = 'puli/public-resource';

    /**
     * The binding parameter used for the server name.
     */
    const SERVER_PARAMETER = 'server';

    /**
     * The binding parameter used for the public path.
     */
    const PATH_PARAMETER = 'path';

    /**
     * @var Discovery
     */
    private $discovery;

    /**
     * @var string[]
     */
    private $urlFormats;

    /**
     * Creates the URL generator.
     *
     * @param Discovery $discovery  The resource discovery.
     * @param string[]  $urlFormats The URL formats indexed by the server names.
     */
    public function __construct(Discovery $discovery, array $urlFormats)
    {
        $this->discovery = $discovery;
        $this->urlFormats = $urlFormats;
    }

    /**
     * {@inheritdoc}
     */
    public function generateUrl($repositoryPath, $currentUrl = null)
    {
        $matchedBinding = null;
        $bindings = $this->discovery->findBindings(self::BINDING_TYPE);

        foreach ($bindings as $binding) {
            /** @var ResourceBinding $binding */
            if (Glob::match($repositoryPath, $binding->getQuery())) {
                $matchedBinding = $binding;
                break;
            }
        }

        if (null === $matchedBinding) {
            throw new CannotGenerateUrlException(sprintf(
                'Cannot generate URL for "%s". The path is not public.',
                $repositoryPath
            ));
        }

        // We can't prevent a resource to be mapped to more than one public path
        // For now, we'll just take the first one and make the user responsible
        // for preventing duplicates
        $url = $this->generateUrlForBinding($matchedBinding, $repositoryPath);

        if ($currentUrl) {
            try {
                $url = Url::makeRelative($url, $currentUrl);
            } catch (InvalidArgumentException $e) {
                throw new CannotGenerateUrlException(sprintf(
                    'Cannot generate URL for "%s" to current url "%s".',
                    $repositoryPath, $currentUrl
                ), $e->getCode(), $e);
            }
        }

        return $url;
    }

    private function generateUrlForBinding(ResourceBinding $binding, $repositoryPath)
    {
        $serverName = $binding->getParameterValue(self::SERVER_PARAMETER);

        if (!isset($this->urlFormats[$serverName])) {
            throw new CannotGenerateUrlException(sprintf(
                'The server "%s" mapped for path "%s" does not exist.',
                $serverName,
                $repositoryPath
            ));
        }

        $repoBasePath = Glob::getStaticPrefix($binding->getQuery());
        $serverBasePath = trim($binding->getParameterValue(self::PATH_PARAMETER), '/');

        // The server path is generated by replacing the base repository path
        // (= the path of the binding) by the stored server base path in the
        // repository path of the resource.
        //
        // Example:
        //
        // resource path: /acme/blog/public/css/style.css
        // binding path: /acme/blog/public{,/**/*}
        // repo base path: /acme/blog/public
        // server base path: /blog
        //
        // final server path: /blog/css/style.css

        $serverPath = substr_replace($repositoryPath, $serverBasePath, 0, strlen($repoBasePath));

        // The server path is inserted into the "%s" parameter of the URL format
        return sprintf($this->urlFormats[$serverName], ltrim($serverPath, '/'));
    }
}
